# Generated by Django 2.2.5 on 2019-11-16 20:49

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='rideStartLoc',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [38.034887, -78.504832], 'marker_color': 'blue'}, null=True, verbose_name='Departure location'),
        ),
    ]
