# Generated by Django 2.2.5 on 2019-11-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0004_ride_deptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='depTime',
        ),
    ]
