# Generated by Django 2.2.5 on 2019-11-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0005_remove_ride_deptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
