# Generated by Django 2.2.5 on 2019-11-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0006_auto_20191116_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login',
            field=models.IntegerField(default=0),
        ),
    ]
