# Generated by Django 2.2.5 on 2019-11-26 20:13

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0007_customuser_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=5, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='startAddress',
            field=models.CharField(default='', max_length=500, verbose_name='Start location'),
        ),
    ]
